import java.awt.*;
import javax.swing.*;
public class CalculatorTwoGUI {
    private JFrame fr;
    private JPanel p1, p2;
    private JTextField txt;
    private JButton btnum_0, btnum_1, btnum_2, btnum_3, btnum_4, btnum_5, btnum_6, btnum_7, btnum_8, btnum_9, btn_1, btn_2, btn_3, btn_4, btn_5, btn_6;
    public CalculatorTwoGUI() {
        fr = new JFrame("My Calculator");
        p1 = new JPanel();
        p2 = new JPanel();
        txt = new JTextField();
        btnum_0 = new JButton("0");
        btnum_1 = new JButton("1");
        btnum_2 = new JButton("2");
        btnum_3 = new JButton("3");
        btnum_4 = new JButton("4");
        btnum_5 = new JButton("5");
        btnum_6 = new JButton("6");
        btnum_7 = new JButton("7");
        btnum_8 = new JButton("8");
        btnum_9 = new JButton("9");
        btn_1 = new JButton("+");
        btn_2 = new JButton("-");
        btn_3 = new JButton("x");
        btn_4 = new JButton("/");
        btn_5 = new JButton("=");
        btn_6 = new JButton("c");
        p1.setLayout(new BorderLayout());
        p2.setLayout(new GridLayout(4,4));
        p2.add(btnum_7);
        p2.add(btnum_8);
        p2.add(btnum_9);
        p2.add(btn_1);
        p2.add(btnum_4);
        p2.add(btnum_5);
        p2.add(btnum_6);
        p2.add(btn_2);
        p2.add(btnum_1);
        p2.add(btnum_2);
        p2.add(btnum_3);
        p2.add(btn_3);
        p2.add(btnum_0);
        p2.add(btn_6);
        p2.add(btn_5);
        p2.add(btn_4);
        p1.add(txt, BorderLayout.NORTH);
        p1.add(p2, BorderLayout.CENTER);
        fr.add(p1);
        fr.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        fr.pack();
        fr.setSize(300, 300);
        fr.setVisible(true);
    }
}
